const MAPSActionTypes = {
  GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
  GET_INPUT_DATA: "GET_INPUT_DATA",
  GET_TOGGLE_SEARCH_RESULT: "GET_TOGGLE_SEARCH_RESULT",
  GET_ADDRESS_PREDICTION: "GET_ADDRESS_PREDICTION"
};
export default MAPSActionTypes;
